### ISSUE TITLE
 small problem

### ISSUE THREAD

**Issue by Xiaoling123456** [serv0id/sarajevo-scraper#1]
I discovered a minor issue with this py. When a problem occurs with a movie (eg. 2227), the preceding one cannot generate a CSV file, particularly if its range is large (eg. 2149-2226).

**Comment by serv0id** [comment]
I don't think any errors would occur now as fixed in the latest commit. Checks have been added to ensure that there are no unsanitized code paths. Kindly comment if anything persists.

Thanks!
