### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Xiaoling123456** [serv0id/sarajevo-scraper#2]
Could you add one more field "Categories", thanks!

**Comment by serv0id** [comment]
![image](https://github.com/serv0id/sarajevo-scraper/assets/113516593/ee97cb4a-2cc7-4404-ac54-e63a11b4a92c)
Do you mean this text in red? For example at https://tickets.sff.ba/films/2150

**Comment by serv0id** [comment]
Added, anyway with https://github.com/serv0id/sarajevo-scraper/commit/7be44d9e551c8d6a384f15975c359d7d51dbaeee

**Comment by Xiaoling123456** [comment]
yes!
